<?php

namespace AppBundle\Repository;

/**
 * ListeAttenteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ListeAttenteRepository extends \Doctrine\ORM\EntityRepository
{
}
